# Generated by Django 4.0.3 on 2022-05-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_core_level_boost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='describtion',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='boost',
            name='name',
            field=models.TextField(default='name'),
        ),
        migrations.AlterField(
            model_name='boost',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
