# Generated by Django 4.0.3 on 2022-06-05 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_boost_type_core_auto_click_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
        migrations.CreateModel(
            name='Achive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField(default='')),
                ('describtion', models.TextField(default='')),
                ('core', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.core')),
            ],
        ),
    ]
