# Generated by Django 4.0.3 on 2022-06-06 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_boost_achiveget_alter_boost_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='boost',
            name='achiveCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boost',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'auto'), (0, 'casual')], default=0),
        ),
    ]
