# Generated by Django 4.0.3 on 2022-06-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0007_boost_achivecount_alter_boost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boost',
            name='achiveCount',
        ),
        migrations.AddField(
            model_name='core',
            name='achiveCount',
            field=models.IntegerField(default=0),
        ),
    ]
